In [21]:
import pandas as pd

In [22]:
pd.DataFrame({'Weight': [50, 45], 'Height': [155, 166]})

   Weight  Height
0      50     155
1      45     166

In [5]:
pd.DataFrame({'Barbie': ['I liked it.', 'It was awful.'],
              'Ken': ['Pretty good.', 'Bland.']},
             index=['Product A', 'Product B'])

                  Barbie           Ken
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

**Ex1**

In [15]:
pd.DataFrame({'Americano': ['20', '25', '18'],
              'Cappuccino': ['22', '30', '21'],
              'Latte': ['23', '29', '10']},
             index=['Coffee Shop #1', 'Coffee Shop #2', 'Coffee Shop #3'])

               Americano Cappuccino Latte
Coffee Shop #1        20         22    23
Coffee Shop #2        25         30    29
Coffee Shop #3        18         21    10

In [16]:
fruits_list = ['Apple', 'Banana', 'Orange','Mango']
fruits_df = pd.DataFrame(fruits_list)
fruits_df

        0
0   Apple
1  Banana
2  Orange
3   Mango

In [19]:
fruits_df = pd.DataFrame(fruits_list, columns=['Fruit'])
fruits_df

    Fruit
0   Apple
1  Banana
2  Orange
3   Mango

**Ex2**

In [10]:
import random
#Generate 10 random numbers between 1 and 100
row1 = random.sample(range(1, 100), 5)
row2 = random.sample(range(1, 100), 5)
row3 = random.sample(range(1, 100), 5)
print(row1)
print(row2)
print(row3)

[15, 91, 71, 74, 1]
[15, 29, 95, 5, 62]
[93, 18, 96, 20, 75]

In [24]:
pd.DataFrame([row1,row2,row2], columns= ["A1", "B2", "C3", "D4", "E5"],index = ["Row #1", "Row #2", "Row #3"])

        A1  B2  C3  D4  E5
Row #1  15  91  71  74   1
Row #2  15  29  95   5  62
Row #3  15  29  95   5  62

In [23]:
df_student=pd.read_csv('/content/ds_students.csv')
df_student

    Student ID                       Name  Age   Score Grade       Province
0    644295001              นายณัฐธีรา เย   31   53.75     D        Songkla
1    644295002        นายณัฐวัฒน์ บุญหวาน   32   37.65     E        Bangkok
2    644295003      นายดนัยเทพ ดำเกลี้ยง    19  ขาดสอบ   NaN      Chiangmai
3    644295004    นางสาวประวีณา พูนเพียร    18      65    C+        Bangkok
4    644295005   นางสาวศุภาพิชญ์ บุญภักดี   21      62     C           Yala
5    644295006       นายรัชชานนท์ ไชยหาญ    20    60.5     C      Chiangrai
6    644295007          นายสฟีร เส็นบัตร    18     NaN   NaN         Phuket
7    644295009            นายซุลฟีฟี มิง    19   51.75     D        Bangkok
8    644295011           นายหิบรีย์ คชสาร   19   64.75     C            Nan
9    644295013    นางสาวแวสาฟียะห์ ดอเลาะ   18   28.25     E          Krabi
10   644295014          นายพชร กาญจนเพชร   -15    24.5     E      Ang Thong
11   644295015      นายตรีภูมิ ช่วยเเท่น    20   56.25    D+        Kalasin
12   644295016    นางสาวเบญญภา ขวัญสว่าง    19   17.25     E   Kanchanaburi
13   644295017      นางสาวอนุสรา แสนอุสา    18   59.63    D+        Lampang
14   644295018     นางสาวจันทิมา ถีราวุฒิ   21    54.5     D        Bangkok
15   644295019       นางสาวตัสนีม ราชนิยม   20   32.75     E   Mae Hong Son
16   644295020           นายฟารุฟ โต๊ะหะ    18      50     D           Loei
17   644295022       นายวีระวัฒน์ ฤทธิ์โต   19    88.5     A  Nakhon Pathom
18   644295023      นายศรีสุภัทรเดช บุบผา   19   29.38     E        Bangkok
19   644295024          นายธนากร นกเขียว    18   75.13     B        Bangkok

In [44]:
reviews=pd.read_csv('/content/winemag-data-5k-v2.csv',index_col=0)
reviews

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",Vulkà Bianco,87,NaN,Sicily & Sardinia,Etna,NaN,Kerin O’Keefe,@kerinokeefe,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",Avidagos,87,15.0,Douro,NaN,NaN,Roger Voss,@vossroger,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",NaN,87,14.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",Reserve Late Harvest,87,13.0,Michigan,Lake Michigan Shore,NaN,Alexander Peartree,NaN,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",Vintner's Reserve Wild Child Block,87,65.0,Oregon,Willamette Valley,Willamette Valley,Paul Gregutt,@paulgwine,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4997,Italy,Candied fruit and caramel ride on the back of ...,Fine Sweet,88,12.0,Sicily & Sardinia,Marsala,NaN,NaN,NaN,Florio NV Fine Sweet (Marsala),Catarratto,Florio
4998,US,This Cabernet Sauvignon-Syrah blend is soft an...,Le Petit Vice,88,50.0,California,Sonoma-Napa,Napa-Sonoma,NaN,NaN,Vice Versa 2005 Le Petit Vice Cabernet Sauvign...,Cabernet Sauvignon-Syrah,Vice Versa
4999,Chile,"Pungent, zesty and quite varietal in its expre...",Reserva Especial,88,19.0,Casablanca Valley,NaN,NaN,Michael Schachner,@wineschach,Viña Mar de Casablanca 2008 Reserva Especial S...,Sauvignon Blanc,Viña Mar de Casablanca
5000,Germany,"Slightly funky and leesy on the nose, with som...",Brauneberger Juffer Kabinett,88,27.0,Mosel-Saar-Ruwer,NaN,NaN,Joe Czerwinski,@JoeCz,Willi Haag 2007 Brauneberger Juffer Kabinett R...,Riesling,Willi Haag
5001,US,Co-fermented with Viognier from the same viney...,Morrison Lane,88,23.0,Washington,Walla Walla Valley (WA),Columbia Valley,Paul Gregutt,@paulgwine,Barrister 2006 Morrison Lane Syrah (Walla Wall...,Syrah,Barrister

In [33]:
reviews.iloc[19:25,:5]

,country,description,designation,points,price
19,US,"Red fruit aromas pervade on the nose, with cig...",NaN,87,32.0
20,US,Ripe aromas of dark berries mingle with ample ...,Vin de Maison,87,23.0
21,US,"A sleek mix of tart berry, stem and herb, alon...",NaN,87,20.0
22,Italy,Delicate aromas recall white flower and citrus...,Ficiligno,87,19.0
23,US,This wine from the Geneseo district offers aro...,Signature Selection,87,22.0
24,Italy,"Aromas of prune, blackcurrant, toast and oak c...",Aynat,87,35.0

In [37]:
reviews.iloc[19:25,[0,2,4]]

   country          designation  price
19      US                  NaN   32.0
20      US        Vin de Maison   23.0
21      US                  NaN   20.0
22   Italy            Ficiligno   19.0
23      US  Signature Selection   22.0
24   Italy                Aynat   35.0

In [47]:
reviews.loc[reviews.country.isin(['Italy', 'Portugal']) & (reviews.price > 55)]

,country,description,designation,points,price,province,region_1,region_2,taster_name,taster_twitter_handle,title,variety,winery
118,Italy,"A blend of 50% Cabernet Sauvignon, 30% Merlot ...",Toscano,87,80.0,Tuscany,Toscana,NaN,Kerin O’Keefe,@kerinokeefe,Tenuta Forconi 2013 Toscano Red (Toscana),Red Blend,Tenuta Forconi
120,Italy,"Slightly backward, particularly given the vint...",Bricco Rocche Prapó,92,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Prapó (Barolo),Nebbiolo,Ceretto
130,Italy,"At the first it was quite muted and subdued, b...",Bricco Rocche Brunate,91,70.0,Piedmont,Barolo,NaN,NaN,NaN,Ceretto 2003 Bricco Rocche Brunate (Barolo),Nebbiolo,Ceretto
133,Italy,"Einaudi's wines have been improving lately, an...",NaN,91,68.0,Piedmont,Barolo,NaN,NaN,NaN,Poderi Luigi Einaudi 2003 Barolo,Nebbiolo,Poderi Luigi Einaudi
135,Italy,The color is just beginning to show signs of b...,Sorano,91,60.0,Piedmont,Barolo,NaN,NaN,NaN,Giacomo Ascheri 2001 Sorano (Barolo),Nebbiolo,Giacomo Ascheri
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4762,Italy,This forward Brunello opens with a fruit and s...,NaN,90,85.0,Tuscany,Brunello di Montalcino,NaN,Kerin O’Keefe,@kerinokeefe,Il Poggione 2009 Brunello di Montalcino,Sangiovese,Il Poggione
4775,Italy,This delivers a classic Sangiovese nose of wil...,Riserva,90,90.0,Tuscany,Brunello di Montalcino,NaN,Kerin O’Keefe,@kerinokeefe,Fattoria dei Barbi 2008 Riserva (Brunello di ...,Sangiovese,Fattoria dei Barbi
4785,Italy,Although the color is an evolved garnet with b...,NaN,90,90.0,Tuscany,Brunello di Montalcino,NaN,Kerin O’Keefe,@kerinokeefe,Tenuta di Sesta 2009 Brunello di Montalcino,Sangiovese,Tenuta di Sesta
4906,Italy,"Perfumed berry, rose petal and baking spice ar...",Bordini,91,62.0,Piedmont,Barbaresco,NaN,Kerin O’Keefe,@kerinokeefe,Fontanabianca 2012 Bordini (Barbaresco),Nebbiolo,Fontanabianca
4916,Portugal,"Straw yellow in color, this now mature wine is...",Monte Cascas Reserva,91,60.0,Tejo,NaN,NaN,Roger Voss,@vossroger,Casca Wines 2010 Monte Cascas Reserva Fernão P...,Fernão Pires,Casca Wines

In [48]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5002 entries, 0 to 5001
Data columns (total 13 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   country                4999 non-null   object
 1   description            5002 non-null   object
 2   designation            3525 non-null   object
 3   points                 5002 non-null   int64
 4   price                  4659 non-null   float64
 5   province               4999 non-null   object
 6   region_1               4209 non-null   object
 7   region_2               1957 non-null   object
 8   taster_name            3971 non-null   object
 9   taster_twitter_handle  3796 non-null   object
 10  title                  5002 non-null   object
 11  variety                5002 non-null   object
 12  winery                 5002 non-null   object
dtypes: float64(1), int64(1), object(11)
memory usage: 547.1+ KB

In [50]:
reviews.describe()

            points        price
count  5002.000000  4659.000000
mean     88.154538    34.733419
std       2.925235    52.310828
min      80.000000     4.000000
25%      86.000000    16.000000
50%      88.000000    25.000000
75%      90.000000    40.000000
max     100.000000  1900.000000

In [54]:
reviews.drop(['designation','region_1','region_2','taster_name','taster_twitter_handle'],
              axis=1,
              inplace=True
            )
reviews.head()

,country,description,points,price,province,title,variety,winery
0,Italy,"Aromas include tropical fruit, broom, brimston...",87,NaN,Sicily & Sardinia,Nicosia 2013 Vulkà Bianco (Etna),White Blend,Nicosia
1,Portugal,"This is ripe and fruity, a wine that is smooth...",87,15.0,Douro,Quinta dos Avidagos 2011 Avidagos Red (Douro),Portuguese Red,Quinta dos Avidagos
2,US,"Tart and snappy, the flavors of lime flesh and...",87,14.0,Oregon,Rainstorm 2013 Pinot Gris (Willamette Valley),Pinot Gris,Rainstorm
3,US,"Pineapple rind, lemon pith and orange blossom ...",87,13.0,Michigan,St. Julian 2013 Reserve Late Harvest Riesling ...,Riesling,St. Julian
4,US,"Much like the regular bottling from 2012, this...",87,65.0,Oregon,Sweet Cheeks 2012 Vintner's Reserve Wild Child...,Pinot Noir,Sweet Cheeks

In [55]:
reviews.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5002 entries, 0 to 5001
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   country      4999 non-null   object
 1   description  5002 non-null   object
 2   points       5002 non-null   int64
 3   price        4659 non-null   float64
 4   province     4999 non-null   object
 5   title        5002 non-null   object
 6   variety      5002 non-null   object
 7   winery       5002 non-null   object
dtypes: float64(1), int64(1), object(6)
memory usage: 351.7+ KB

In [56]:
reviews.describe()

            points        price
count  5002.000000  4659.000000
mean     88.154538    34.733419
std       2.925235    52.310828
min      80.000000     4.000000
25%      86.000000    16.000000
50%      88.000000    25.000000
75%      90.000000    40.000000
max     100.000000  1900.000000

In [60]:
reviews.price.fillna(reviews.price.mean(),inplace=True)
reviews.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5002 entries, 0 to 5001
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   country      4999 non-null   object
 1   description  5002 non-null   object
 2   points       5002 non-null   int64
 3   price        5002 non-null   float64
 4   province     4999 non-null   object
 5   title        5002 non-null   object
 6   variety      5002 non-null   object
 7   winery       5002 non-null   object
dtypes: float64(1), int64(1), object(6)
memory usage: 351.7+ KB

/tmp/ipython-input-2358042147.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  reviews.price.fillna(reviews.price.mean(),inplace=True)

In [61]:
reviews.country.fillna(reviews.country.mode()[0],inplace=True)
reviews.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5002 entries, 0 to 5001
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   country      5002 non-null   object
 1   description  5002 non-null   object
 2   points       5002 non-null   int64
 3   price        5002 non-null   float64
 4   province     4999 non-null   object
 5   title        5002 non-null   object
 6   variety      5002 non-null   object
 7   winery       5002 non-null   object
dtypes: float64(1), int64(1), object(6)
memory usage: 351.7+ KB

/tmp/ipython-input-1397964644.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  reviews.country.fillna(reviews.country.mode()[0],inplace=True)

In [62]:
reviews.province.fillna(reviews.province.mode()[0],inplace=True)
reviews.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5002 entries, 0 to 5001
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   country      5002 non-null   object
 1   description  5002 non-null   object
 2   points       5002 non-null   int64
 3   price        5002 non-null   float64
 4   province     5002 non-null   object
 5   title        5002 non-null   object
 6   variety      5002 non-null   object
 7   winery       5002 non-null   object
dtypes: float64(1), int64(1), object(6)
memory usage: 351.7+ KB

/tmp/ipython-input-2484701686.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  reviews.province.fillna(reviews.province.mode()[0],inplace=True)