In [1]:
import pandas as pd

In [9]:
std = pd.read_csv('/content/drive/MyDrive/DataScience/Datasets/ds_students.csv')
std

    Student ID                       Name  Age   Score Grade       Province
0    644295001              นายณัฐธีรา เย   31   53.75     D        Songkla
1    644295002        นายณัฐวัฒน์ บุญหวาน   32   37.65     E        Bangkok
2    644295003      นายดนัยเทพ ดำเกลี้ยง    19  ขาดสอบ   NaN      Chiangmai
3    644295004    นางสาวประวีณา พูนเพียร    18      65    C+        Bangkok
4    644295005   นางสาวศุภาพิชญ์ บุญภักดี   21      62     C           Yala
5    644295006       นายรัชชานนท์ ไชยหาญ    20    60.5     C      Chiangrai
6    644295007          นายสฟีร เส็นบัตร    18     NaN   NaN         Phuket
7    644295009            นายซุลฟีฟี มิง    19   51.75     D        Bangkok
8    644295011           นายหิบรีย์ คชสาร   19   64.75     C            Nan
9    644295013    นางสาวแวสาฟียะห์ ดอเลาะ   18   28.25     E          Krabi
10   644295014          นายพชร กาญจนเพชร   -15    24.5     E      Ang Thong
11   644295015      นายตรีภูมิ ช่วยเเท่น    20   56.25    D+        Kalasin
12   644295016    นางสาวเบญญภา ขวัญสว่าง    19   17.25     E   Kanchanaburi
13   644295017      นางสาวอนุสรา แสนอุสา    18   59.63    D+        Lampang
14   644295018     นางสาวจันทิมา ถีราวุฒิ   21    54.5     D        Bangkok
15   644295019       นางสาวตัสนีม ราชนิยม   20   32.75     E   Mae Hong Son
16   644295020           นายฟารุฟ โต๊ะหะ    18      50     D           Loei
17   644295022       นายวีระวัฒน์ ฤทธิ์โต   19    88.5     A  Nakhon Pathom
18   644295023      นายศรีสุภัทรเดช บุบผา   19   29.38     E        Bangkok
19   644295024          นายธนากร นกเขียว    18   75.13     B        Bangkok

In [10]:
std.describe()

         Student ID        Age
count  2.000000e+01  20.000000
mean   6.442950e+08  18.600000
std    7.437282e+00   8.834144
min    6.442950e+08 -15.000000
25%    6.442950e+08  18.000000
50%    6.442950e+08  19.000000
75%    6.442950e+08  20.000000
max    6.442950e+08  32.000000

In [11]:
std.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student ID  20 non-null     int64
 1   Name        20 non-null     object
 2   Age         20 non-null     int64
 3   Score       19 non-null     object
 4   Grade       18 non-null     object
 5   Province    20 non-null     object
dtypes: int64(2), object(4)
memory usage: 1.1+ KB

In [12]:
std.isnull().sum()

Student ID    0
Name          0
Age           0
Score         1
Grade         2
Province      0
dtype: int64

In [13]:
std.loc[std['Score']=='ขาดสอบ','Score']=0
std

    Student ID                       Name  Age  Score Grade       Province
0    644295001              นายณัฐธีรา เย   31  53.75     D        Songkla
1    644295002        นายณัฐวัฒน์ บุญหวาน   32  37.65     E        Bangkok
2    644295003      นายดนัยเทพ ดำเกลี้ยง    19      0   NaN      Chiangmai
3    644295004    นางสาวประวีณา พูนเพียร    18     65    C+        Bangkok
4    644295005   นางสาวศุภาพิชญ์ บุญภักดี   21     62     C           Yala
5    644295006       นายรัชชานนท์ ไชยหาญ    20   60.5     C      Chiangrai
6    644295007          นายสฟีร เส็นบัตร    18    NaN   NaN         Phuket
7    644295009            นายซุลฟีฟี มิง    19  51.75     D        Bangkok
8    644295011           นายหิบรีย์ คชสาร   19  64.75     C            Nan
9    644295013    นางสาวแวสาฟียะห์ ดอเลาะ   18  28.25     E          Krabi
10   644295014          นายพชร กาญจนเพชร   -15   24.5     E      Ang Thong
11   644295015      นายตรีภูมิ ช่วยเเท่น    20  56.25    D+        Kalasin
12   644295016    นางสาวเบญญภา ขวัญสว่าง    19  17.25     E   Kanchanaburi
13   644295017      นางสาวอนุสรา แสนอุสา    18  59.63    D+        Lampang
14   644295018     นางสาวจันทิมา ถีราวุฒิ   21   54.5     D        Bangkok
15   644295019       นางสาวตัสนีม ราชนิยม   20  32.75     E   Mae Hong Son
16   644295020           นายฟารุฟ โต๊ะหะ    18     50     D           Loei
17   644295022       นายวีระวัฒน์ ฤทธิ์โต   19   88.5     A  Nakhon Pathom
18   644295023      นายศรีสุภัทรเดช บุบผา   19  29.38     E        Bangkok
19   644295024          นายธนากร นกเขียว    18  75.13     B        Bangkok

In [14]:
std['Score'] = std['Score'].astype(float)
std.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student ID  20 non-null     int64
 1   Name        20 non-null     object
 2   Age         20 non-null     int64
 3   Score       19 non-null     float64
 4   Grade       18 non-null     object
 5   Province    20 non-null     object
dtypes: float64(1), int64(2), object(3)
memory usage: 1.1+ KB

In [16]:
std['Score'].fillna(0,inplace=True)
std.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student ID  20 non-null     int64
 1   Name        20 non-null     object
 2   Age         20 non-null     int64
 3   Score       20 non-null     float64
 4   Grade       18 non-null     object
 5   Province    20 non-null     object
dtypes: float64(1), int64(2), object(3)
memory usage: 1.1+ KB

/tmp/ipython-input-795330738.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  std['Score'].fillna(0,inplace=True)

In [42]:
std['Grade'].fillna('E',inplace=True)
std.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student ID  20 non-null     int64
 1   Name        20 non-null     object
 2   Age         20 non-null     int64
 3   Score       20 non-null     float64
 4   Grade       20 non-null     object
 5   Province    20 non-null     object
dtypes: float64(1), int64(2), object(3)
memory usage: 1.1+ KB

In [46]:
std.describe()

         Student ID      Score
count  2.000000e+01  20.000000
mean   6.442950e+08  45.577000
std    7.437282e+00  23.686149
min    6.442950e+08   0.000000
25%    6.442950e+08  29.097500
50%    6.442950e+08  52.750000
75%    6.442950e+08  60.875000
max    6.442950e+08  88.500000

In [49]:
std.drop(['Name','Age'], axis=1, inplace=True)

KeyError: "['Name', 'Age'] not found in axis"

In [50]:
std.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student ID  20 non-null     int64
 1   Score       20 non-null     float64
 2   Grade       20 non-null     object
 3   Province    20 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 772.0+ bytes